/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/test.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useState } from 'react';
import { useFrame } from '@react-three/fiber';

export function Room(props) {
  const { nodes, materials } = useGLTF('public/models/test.glb')
  const [isHovered, setIsHovered] = useState(false);
  const [isClicked, setIsClicked] = useState(false);
  
  return (
    <group {...props} dispose={null}>
    <mesh geometry={nodes.Plane.geometry} material={materials['vägg.002']} position={[0.057, 0, 0]} scale={[0.947, 1, 1]} />
    <mesh geometry={nodes.Cube064.geometry} material={materials['Material.001']} position={[0.79, 0.153, 0]} scale={-0.148} />
    <mesh geometry={nodes.Cube065.geometry} material={materials['hylla.002']} position={[-0.359, 0.419, 0.855]} scale={[0.462, 0.014, 0.15]} />
    <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} position={[-0.673, 0.55, 0.821]} scale={0.135} />
    <mesh geometry={nodes.Cube.geometry} material={materials['floor.001']} position={[0.937, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube001.geometry} material={materials['floor.001']} position={[0.937, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube002.geometry} material={materials['floor.001']} position={[0.937, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube003.geometry} material={materials['floor.001']} position={[0.937, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube004.geometry} material={materials['floor.001']} position={[0.819, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube005.geometry} material={materials['floor.001']} position={[0.819, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube006.geometry} material={materials['floor.001']} position={[0.819, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube007.geometry} material={materials['floor.001']} position={[0.819, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube008.geometry} material={materials['floor.001']} position={[0.701, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube009.geometry} material={materials['floor.001']} position={[0.701, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube010.geometry} material={materials['floor.001']} position={[0.701, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube011.geometry} material={materials['floor.001']} position={[0.701, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube012.geometry} material={materials['floor.001']} position={[0.58, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube013.geometry} material={materials['floor.001']} position={[0.58, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube014.geometry} material={materials['floor.001']} position={[0.58, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube015.geometry} material={materials['floor.001']} position={[0.58, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube016.geometry} material={materials['floor.001']} position={[0.464, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube017.geometry} material={materials['floor.001']} position={[0.464, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube018.geometry} material={materials['floor.001']} position={[0.464, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube019.geometry} material={materials['floor.001']} position={[0.464, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube020.geometry} material={materials['floor.001']} position={[0.345, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube021.geometry} material={materials['floor.001']} position={[0.345, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube022.geometry} material={materials['floor.001']} position={[0.345, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube023.geometry} material={materials['floor.001']} position={[0.345, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube024.geometry} material={materials['floor.001']} position={[0.227, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube025.geometry} material={materials['floor.001']} position={[0.227, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube026.geometry} material={materials['floor.001']} position={[0.227, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube027.geometry} material={materials['floor.001']} position={[0.227, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube028.geometry} material={materials['floor.001']} position={[0.107, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube029.geometry} material={materials['floor.001']} position={[0.107, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube030.geometry} material={materials['floor.001']} position={[0.107, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube031.geometry} material={materials['floor.001']} position={[0.107, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube032.geometry} material={materials['floor.001']} position={[-0.009, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube033.geometry} material={materials['floor.001']} position={[-0.009, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube034.geometry} material={materials['floor.001']} position={[-0.009, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube035.geometry} material={materials['floor.001']} position={[-0.009, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube036.geometry} material={materials['floor.001']} position={[-0.127, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube037.geometry} material={materials['floor.001']} position={[-0.127, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube038.geometry} material={materials['floor.001']} position={[-0.127, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube039.geometry} material={materials['floor.001']} position={[-0.127, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube040.geometry} material={materials['floor.001']} position={[-0.245, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube041.geometry} material={materials['floor.001']} position={[-0.245, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube042.geometry} material={materials['floor.001']} position={[-0.245, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube043.geometry} material={materials['floor.001']} position={[-0.245, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube044.geometry} material={materials['floor.001']} position={[-0.366, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube045.geometry} material={materials['floor.001']} position={[-0.366, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube046.geometry} material={materials['floor.001']} position={[-0.366, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube047.geometry} material={materials['floor.001']} position={[-0.366, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube048.geometry} material={materials['floor.001']} position={[-0.483, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube049.geometry} material={materials['floor.001']} position={[-0.483, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube050.geometry} material={materials['floor.001']} position={[-0.483, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube051.geometry} material={materials['floor.001']} position={[-0.483, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube052.geometry} material={materials['floor.001']} position={[-0.601, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube053.geometry} material={materials['floor.001']} position={[-0.601, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube054.geometry} material={materials['floor.001']} position={[-0.601, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube055.geometry} material={materials['floor.001']} position={[-0.601, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube056.geometry} material={materials['floor.001']} position={[-0.72, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube057.geometry} material={materials['floor.001']} position={[-0.72, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube058.geometry} material={materials['floor.001']} position={[-0.72, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube059.geometry} material={materials['floor.001']} position={[-0.72, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube060.geometry} material={nodes.Cube060.material} position={[-0.84, 0, -0.69]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube061.geometry} material={materials['floor.001']} position={[-0.84, 0, -0.059]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube062.geometry} material={materials['floor.001']} position={[-0.84, 0, 0.572]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cube063.geometry} material={materials['floor.001']} position={[-0.84, 0, 1.205]} rotation={[0, 0, -Math.PI]} scale={[0.057, 0.003, 0.315]} />
    <mesh geometry={nodes.Cone.geometry} material={materials['lamp.003']} position={[0.204, 1.566, 0.131]} scale={0.168} />
  </group>
  )
}

useGLTF.preload('public/models/test.glb')

